# Generated by Django 5.2.4 on 2025-07-26 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=75)),
                ('email', models.TextField()),
                ('icon', models.ImageField(blank=True, default='fallback.png', upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
